services:
  - type: web
    name: futureme
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn futureme.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: futureme.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: futureme-db
          property: connectionString

databases:
  - name: futureme-db
    databaseName: futureme
    user: futureme
    plan: free 